jobs:
- job: FirstAcunetixJob
  displayName: First Acunetix Job
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CmdLine@2
    inputs:
      script: 'curl -k -i --request POST --url https://online.acunetix.com/api/v1/scans --header "X-Auth: 1986ad8c0a5b3df4d7028d5f3c06e936ceed683f936b44385b60e1ae7aec899f1" --header "content-type: application/json" --data "{ \"profile_id\" : \"11111111-1111-1111-1111-111111111111\" , \"incremental\" : false , \"schedule\" : { \"disable\" : false , \"start_date\" : null , \"time_sensitive\" : false } , \"user_authorized_to_scan\" : \"yes\" , \"target_id\" : \"9930d31f-aca7-404d-9cc7-624969e7aa82\" }"'
